### ISSUE TITLE
Rspec error action controller

### ISSUE THREAD

**Issue by gkonczol** [moehnked/cs362_CarCaptor#9]
...............FFF

Failures:

  1) adding a car allows a user to create a car
     Failure/Error: visit new_car_path

     ActionController::UnknownFormat:
       CarsController#new is missing a template for this request format and variant.

       request.formats: ["text/html"]
       request.variant: []

       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.

     # ./spec/system/add_car_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) adding a unique car allows a car to be added to a new user
     Failure/Error: visit new_car_path

     ActionController::UnknownFormat:
       CarsController#new is missing a template for this request format and variant.

       request.formats: ["text/html"]
       request.variant: []

       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.

     # ./spec/system/add_unique_car_spec.rb:5:in `block (2 levels) in <top (required)>'

  3) adding a user allows a new user to be created
     Failure/Error: visit new_user_path

     ActionController::UnknownFormat:
       UsersController#new is missing a template for this request format and variant.

       request.formats: ["text/html"]
       request.variant: []

       NOTE! For XHR/Ajax or API requests, this action would normally respond with 204 No Content: an empty white screen. Since you're loading it in a web browser, we assume that you expected to actually render a template, not nothing, so we're showing an error to be extra-clear. If you expect 204 No Content, carry on. That's what you'll get from an XHR or API request. Give it a shot.

     # ./spec/system/add_user_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 6.25 seconds (files took 12.83 seconds to load)
18 examples, 3 failures

Failed examples:

rspec ./spec/system/add_car_spec.rb:4 # adding a car allows a user to create a car
rspec ./spec/system/add_unique_car_spec.rb:4 # adding a unique car allows a car to be added to a new user
rspec ./spec/system/add_user_spec.rb:4 # adding a user allows a new user to be created

**Comment by gkonczol** [comment]
Fixed by installing Ubuntu.
